# ----
# Site

title: HassleFree Solutions, LLC.
url: "https://hasslefree.solutions"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:
email: hello@hasslefree.solutions

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: The official homepage for HassleFree Solutions, LLC.
author:
  name: Alcha
  email: alcha@hasslefree.solutions
  twitter: 4lch4
social:
  name: HassleFree Solutions
  links:
    - https://github.com/HF-Solutions
    - https://twitter.com/HF_Solutionz
    - https://www.upwork.com/fl/alcha
    - https://facebook.com/HassleFreeSolutions/

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"

permalink: /blog/:year/:month/:day/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - LinkedIn
  - Twitter
  - RSS
